// Seed data for Circuito Jovem Sustentável
// This provides initial data for testing and presentation

export const seedStations = [
  {
    id: '1',
    nome: 'UFPE - Centro de Tecnologia',
    endereco: 'Av. Prof. Moraes Rego, 1235',
    bairro: 'Cidade Universitária',
    latitude: -8.0522,
    longitude: -34.9514,
    tipos_aceitos: ['plástico', 'papel', 'metal', 'vidro', 'eletrônico'],
    horario_funcionamento: 'Seg-Sex 8h-18h',
    capacidade_atual: 45,
    total_kg_coletados: 2340.5,
    ativa: true,
  },
  {
    id: '2',
    nome: 'UNICAP - Campus Boa Vista',
    endereco: 'Rua do Príncipe, 526',
    bairro: 'Boa Vista',
    latitude: -8.0596,
    longitude: -34.8770,
    tipos_aceitos: ['plástico', 'papel', 'metal', 'vidro'],
    horario_funcionamento: 'Seg-Sex 7h-19h',
    capacidade_atual: 62,
    total_kg_coletados: 1876.2,
    ativa: true,
  },
  {
    id: '3',
    nome: 'UPE - Faculdade de Engenharia',
    endereco: 'Rua Benfica, 455',
    bairro: 'Madalena',
    latitude: -8.0338,
    longitude: -34.9077,
    tipos_aceitos: ['plástico', 'papel', 'metal'],
    horario_funcionamento: 'Seg-Sex 8h-17h',
    capacidade_atual: 28,
    total_kg_coletados: 892.7,
    ativa: true,
  },
  {
    id: '4',
    nome: 'Centro Acadêmico Boa Viagem',
    endereco: 'Av. Conselheiro Aguiar, 3351',
    bairro: 'Boa Viagem',
    latitude: -8.1177,
    longitude: -34.8996,
    tipos_aceitos: ['plástico', 'papel', 'vidro'],
    horario_funcionamento: 'Seg-Sáb 9h-20h',
    capacidade_atual: 73,
    total_kg_coletados: 1523.8,
    ativa: true,
  },
  {
    id: '5',
    nome: 'Ponto Verde Casa Amarela',
    endereco: 'Rua Real da Torre, 987',
    bairro: 'Casa Amarela',
    latitude: -8.0302,
    longitude: -34.9155,
    tipos_aceitos: ['plástico', 'papel', 'metal', 'vidro', 'eletrônico'],
    horario_funcionamento: 'Seg-Sex 9h-18h, Sáb 9h-13h',
    capacidade_atual: 51,
    total_kg_coletados: 2105.3,
    ativa: true,
  },
];

export const seedRewards = [
  {
    id: '1',
    comercio_nome: 'Café do Alto',
    titulo: '20% OFF em Café Especial',
    descricao: 'Ganhe 20% de desconto em qualquer café especial da casa. Válido para café coado, espresso, cappuccino e mais.',
    tipo: 'desconto',
    valor_desconto: '20%',
    chaves_necessarias: 50,
    nivel_necessario: 'Iniciante',
    quantidade_disponivel: 100,
    quantidade_resgatada: 23,
    categoria: 'Café',
    bairro: 'Boa Vista',
    imagem_url: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085',
    ativa: true,
  },
  {
    id: '2',
    comercio_nome: 'Pizza na Pedra',
    titulo: 'Pizza Grande + Refrigerante',
    descricao: 'Combo especial: Pizza grande (até 3 sabores) + Refrigerante 2L. Válido de segunda a quinta.',
    tipo: 'desconto',
    valor_desconto: 'R$ 15',
    chaves_necessarias: 120,
    nivel_necessario: 'Bronze',
    quantidade_disponivel: 50,
    quantidade_resgatada: 12,
    categoria: 'Restaurante',
    bairro: 'Casa Forte',
    imagem_url: 'https://images.unsplash.com/photo-1513104890138-7c749659a591',
    ativa: true,
  },
  {
    id: '3',
    comercio_nome: 'Cinema São Luiz',
    titulo: 'Ingresso Meia-Entrada',
    descricao: 'Ingresso com valor de meia-entrada para qualquer sessão. Válido de segunda a quinta (exceto feriados).',
    tipo: 'desconto',
    valor_desconto: '50%',
    chaves_necessarias: 200,
    nivel_necessario: 'Bronze',
    quantidade_disponivel: -1,
    quantidade_resgatada: 45,
    categoria: 'Cinema',
    bairro: 'Recife Antigo',
    imagem_url: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba',
    ativa: true,
  },
  {
    id: '4',
    comercio_nome: 'Livraria Cultura',
    titulo: 'Vale-Compras de R$ 30',
    descricao: 'Vale-compras de R$ 30 para usar em livros, papelaria ou eletrônicos. Não é cumulativo com outras promoções.',
    tipo: 'brinde',
    valor_desconto: 'R$ 30',
    chaves_necessarias: 300,
    nivel_necessario: 'Prata',
    quantidade_disponivel: 30,
    quantidade_resgatada: 8,
    categoria: 'Cultura',
    bairro: 'Boa Viagem',
    imagem_url: 'https://images.unsplash.com/photo-1507842217343-583bb7270b66',
    ativa: true,
  },
  {
    id: '5',
    comercio_nome: 'Academia EcoFit',
    titulo: '1 Mês de Musculação Grátis',
    descricao: 'Acesso exclusivo: 1 mês completo de musculação + avaliação física. Para novos alunos do Circuito Jovem.',
    tipo: 'acesso_exclusivo',
    valor_desconto: '1 mês grátis',
    chaves_necessarias: 500,
    nivel_necessario: 'Ouro',
    quantidade_disponivel: 20,
    quantidade_resgatada: 3,
    categoria: 'Lazer',
    bairro: 'Espinheiro',
    imagem_url: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48',
    ativa: true,
  },
  {
    id: '6',
    comercio_nome: 'Paço Alfândega',
    titulo: 'Tour Gastronômico Premium',
    descricao: 'Experiência exclusiva: Tour guiado por 5 restaurantes do shopping com degustação em cada. Máximo 2 pessoas.',
    tipo: 'experiencia',
    valor_desconto: 'Experiência única',
    chaves_necessarias: 800,
    nivel_necessario: 'Ouro',
    quantidade_disponivel: 10,
    quantidade_resgatada: 1,
    categoria: 'Restaurante',
    bairro: 'Recife Antigo',
    imagem_url: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0',
    ativa: true,
  },
  {
    id: '7',
    comercio_nome: 'Oficina Francisco Brennand',
    titulo: 'Ingresso VIP + Workshop',
    descricao: 'Acesso VIP à Oficina Brennand + Workshop de cerâmica com artista local. Experiência completa de 4 horas.',
    tipo: 'experiencia',
    valor_desconto: 'Experiência exclusiva',
    chaves_necessarias: 1000,
    nivel_necessario: 'Diamante',
    quantidade_disponivel: 5,
    quantidade_resgatada: 0,
    categoria: 'Cultura',
    bairro: 'Várzea',
    imagem_url: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f',
    ativa: true,
  },
  {
    id: '8',
    comercio_nome: 'Caxangá Golf Club',
    titulo: 'Aula de Golf Particular',
    descricao: 'Aula particular de golf de 2 horas com instrutor profissional + kit iniciante. Apenas níveis Diamante.',
    tipo: 'acesso_exclusivo',
    valor_desconto: 'Aula premium',
    chaves_necessarias: 1200,
    nivel_necessario: 'Diamante',
    quantidade_disponivel: 8,
    quantidade_resgatada: 0,
    categoria: 'Lazer',
    bairro: 'Casa Forte',
    imagem_url: 'https://images.unsplash.com/photo-1535131749006-b7f58c99034b',
    ativa: true,
  },
  {
    id: '9',
    comercio_nome: 'Hamburgueria Artesanal',
    titulo: 'Combo Burger + Batata + Shake',
    descricao: 'Combo completo: Burger artesanal de 200g (4 opções) + Batata rústica + Milkshake. Válido todos os dias.',
    tipo: 'desconto',
    valor_desconto: 'R$ 10',
    chaves_necessarias: 80,
    nivel_necessario: 'Iniciante',
    quantidade_disponivel: -1,
    quantidade_resgatada: 67,
    categoria: 'Restaurante',
    bairro: 'Pina',
    imagem_url: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd',
    ativa: true,
  },
  {
    id: '10',
    comercio_nome: 'Teatro do Parque',
    titulo: '2 Ingressos para Espetáculo',
    descricao: 'Dois ingressos para qualquer espetáculo em cartaz. Sujeito à disponibilidade. Válido por 3 meses.',
    tipo: 'brinde',
    valor_desconto: '2 ingressos',
    chaves_necessarias: 350,
    nivel_necessario: 'Prata',
    quantidade_disponivel: 25,
    quantidade_resgatada: 7,
    categoria: 'Cultura',
    bairro: 'Casa Forte',
    imagem_url: 'https://images.unsplash.com/photo-1503095396549-807759245b35',
    ativa: true,
  },
];

export const seedInstitutions = [
  {
    id: '1',
    nome: 'Universidade Federal de Pernambuco - UFPE',
    tipo: 'Universidade',
    endereco: 'Av. Prof. Moraes Rego, 1235',
    bairro: 'Cidade Universitária',
    latitude: -8.0522,
    longitude: -34.9514,
    telefone: '(81) 2126-8000',
  },
  {
    id: '2',
    nome: 'Universidade Católica de Pernambuco - UNICAP',
    tipo: 'Universidade',
    endereco: 'Rua do Príncipe, 526',
    bairro: 'Boa Vista',
    latitude: -8.0596,
    longitude: -34.8770,
    telefone: '(81) 2119-4000',
  },
  {
    id: '3',
    nome: 'Universidade de Pernambuco - UPE',
    tipo: 'Universidade',
    endereco: 'Rua Benfica, 455',
    bairro: 'Madalena',
    latitude: -8.0338,
    longitude: -34.9077,
    telefone: '(81) 3183-3600',
  },
];

export const materialMultipliers = {
  'eletrônico': 20,
  'eletronico': 20,
  'metal': 15,
  'vidro': 12,
  'plástico': 10,
  'plastico': 10,
  'papel': 8,
};

export const niveis = [
  { nome: 'Iniciante', min: 0, max: 99, cor: '#8B8B8B' },
  { nome: 'Bronze', min: 100, max: 299, cor: '#CD7F32' },
  { nome: 'Prata', min: 300, max: 599, cor: '#C0C0C0' },
  { nome: 'Ouro', min: 600, max: 999, cor: '#FFD700' },
  { nome: 'Diamante', min: 1000, max: Infinity, cor: '#B9F2FF' },
];

export function getNivelFromChaves(chaves: number) {
  return niveis.find(n => chaves >= n.min && chaves <= n.max) || niveis[0];
}

export function calculateChavesFromColeta(tipo_material: string, peso_kg: number): number {
  const multiplier = materialMultipliers[tipo_material.toLowerCase()] || 10;
  return Math.floor(peso_kg * multiplier);
}
